osx_image: xcode10.1
language: objective-c
branches:
  only:
    - master
    - develop
notifications:
  email: false
cache:
  directories:
  - Carthage
before_install:
  - gem install cocoapods --pre
  - gem install bundler
  - gem install fastlane -NV
  - bundle install
  - npm install bumped -g

  - carthage update --cache-builds
before_script:
  - bumped release patch
script: bundle exec fastlane build --repo-update
