osx_image: xcode10.1
language: objective-c
branches:
  only:
    - master
notifications:
  email: false
before_install:
  - gem install bundler
  - gem install fastlane -NV
  - bundle install
  - npm install bumped -g
before_script:
  - bumped release patch
script: bundle exec fastline release
